INSERT INTO PRODUCT (TITRE, DESCRIPTION, IMAGE, PRIX) VALUES ('P1','Desc 1','img1.png',100);
INSERT INTO PRODUCT (TITRE, DESCRIPTION, IMAGE, PRIX) VALUES ('P2','Desc 2','img2.png',200);
INSERT INTO PRODUCT (TITRE, DESCRIPTION, IMAGE, PRIX) VALUES ('P3','Desc 3','img3.png',300);
INSERT INTO PRODUCT (TITRE, DESCRIPTION, IMAGE, PRIX) VALUES ('P4','Desc 4','img4.png',400);
INSERT INTO PRODUCT (TITRE, DESCRIPTION, IMAGE, PRIX) VALUES ('P5','Desc 5','img5.png',500);
INSERT INTO PRODUCT (TITRE, DESCRIPTION, IMAGE, PRIX) VALUES ('P6','Desc 6','img6.png',600);
INSERT INTO PRODUCT (TITRE, DESCRIPTION, IMAGE, PRIX) VALUES ('P7','Desc 7','img7.png',700);
INSERT INTO PRODUCT (TITRE, DESCRIPTION, IMAGE, PRIX) VALUES ('P8','Desc 8','img8.png',800);
